services:
  app:
    image: client-myevents-dev
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes: 
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 5173:5173
    container_name: client-myevents-dev