@host = http://localhost:3003
@eventId = 670bddbdc15ac8ad9324bb49
@apiversion = /api/v1

### Create a new event
POST {{host}}{{apiversion}}/events
Content-Type: application/json

{
  "name": "AI for everyone",
  "description": "A fundamental of AI for beginners",
  "location": "670535642a5a13d07b8b412f",
  "organizer": "67013529a2556b0192e1acfb",
  "date": "2026-12-01T14:00:00.000Z",
  "price": 150,
  "event_link": "https://example.com/ai-conference",
  "event_type": "conference",
  "attendees": []
}

### Chat to find Events with AI
POST {{host}}{{apiversion}}/events/ai
Content-Type: application/json

{
  "message": "I plan to go somewhere with my friends but I do not have that much money, can you recommend me some affordable events?"
}

### Continue the chat
POST {{host}}{{apiversion}}/events/ai/1728831198287
Content-Type: application/json

{
  "message": "As I know that maybe there is a event named AI for everyone, can you provide me more details?"
}

### Get event by ID
GET {{host}}{{apiversion}}/events/{{eventId}}

### Fetch all events with pagination
GET {{host}}{{apiversion}}/events?page=1&limit=10

### Update event by ID (partial update - only date)
PUT {{host}}{{apiversion}}/events/{{eventId}}
Content-Type: application/json

{
  "date": "2024-10-15T10:00:00.000Z"
}

### Update event by ID (partial update - only price)
PUT {{host}}{{apiversion}}/events/{{eventId}}
Content-Type: application/json

{
  "price": 300
}

### Delete event by ID
DELETE {{host}}{{apiversion}}/events/{{eventId}}
