@host = http://localhost:3003
@eventId = 66e47b5bc7fd3303b57c8f0b
@apiversion = /api/v1

### Create a new event
POST {{host}}{{apiversion}}/events
Content-Type: application/json

{
  "name": "Music Fest 2024",
  "description": "A Music concert",
  "location": "67014f3b42f85f6b4dc669d8",
  "organizer": "67013529a2556b0192e1acfb",
  "date": "2024-09-20T18:30:00.000Z",
  "price": 250,
  "event_link": "https://techconf2024.com",
  "event_type": "concert",
  "attendees": []
}

### Get event by ID
GET {{host}}{{apiversion}}/events/{{eventId}}

### Fetch all events with pagination
GET {{host}}{{apiversion}}/events?page=1&limit=10

### Update event by ID (partial update - only date)
PUT {{host}}{{apiversion}}/events/{{eventId}}
Content-Type: application/json

{
  "date": "2024-10-15T10:00:00.000Z"
}

### Update event by ID (partial update - only price)
PUT {{host}}{{apiversion}}/events/{{eventId}}
Content-Type: application/json

{
  "price": 300
}

### Delete event by ID
DELETE {{host}}{{apiversion}}/events/{{eventId}}
