### Create a new location
POST http://localhost:3003/api/locations
Content-Type: application/json

{
  "latitude": 60.1699,
  "longitude": 24.9384,
  "address": {
    "country": "Finland",
    "city": "Helsinki",
    "district": "Kallio",
    "post_code": "00530"
  }
}

### Get location by ID
GET http://localhost:3003/api/locations/66e31ff0444a4d55c59828a7