@host = http://localhost:3003
@apiversion = /api/v1
@userId = 66ead78b49bac489378931f2
@jwtToken= eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2ZTQ3MzZhZjQ1MmY3M2M0ZmRiMDE5NiIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzI3ODg0NjcxLCJleHAiOjE3Mjc4ODgyNzF9.OHskTcCkDC1UVYxfgrOIYoq-MQ4a2KwzJYekRntvfzM
@refreshToken = your_refresh_token_here
@userEmail = john@example.com

### Create a new user
POST {{host}}/api/users 
Content-Type: application/json

{
  "name": "Alice Johnson",
  "email": "alice.johnson@example.com",
  "password": "Password123!",
  "role": "organizer"
}

### Get all users (with pagination)
GET {{host}}/api/users?page=1&limit=10

### Get a user by ID
GET {{host}}/api/users/{{userId}}

### Update a user by ID
PUT {{host}}/api/users/{{userId}}
Content-Type: application/json

{
  "name": "Michael Smith Updated",
  "email": "michael.smith@example.com"
}

### Delete a user by ID
DELETE {{host}}/api/users/{{userId}}