@host = http://localhost:3003

### Create a new address
POST {{host}}/api/addresses
Content-Type: application/json

{
  "country": "Finland",
  "city": "Helsinki",
  "district": "Kallio",
  "post_code": "00530"
}


### Get All addresses
GET {{host}}/api/addresses

### Get address by ID
GET {{host}}/api/addresses/66e939c045c8ab4b09b6cf0c

### Update address
PUT {{host}}/api/addresses/66e9392fd6d214e059a0a207
Content-Type: application/json

{
  "country": "Finland",
  "city": "Vaasa",
  "district": "Leipatehdas",
  "post_code": "65100"
}

### Delete address
DELETE {{host}}/api/addresses/66e93a2345c8ab4b09b6cf10