@host = http://localhost:3003
@apiversion = /api/v1
@address_id = 66ebc74a19656827a51dc2e5

### Create a new location
POST {{host}}{{apiversion}}/locations
Content-Type: application/json

{
  "latitude": 60.1699,
  "longitude": 24.9384,
  "address": "{{address_id}}"
}

### Get All locations
GET {{host}}{{apiversion}}/locations

### Get location by ID
GET {{host}}{{apiversion}}/locations/66ebcc73dc764104700dced7

### Update location
PUT {{host}}{{apiversion}}/locations/66ebcc73dc764104700dced7
Content-Type: application/json

{
  "latitude": 60.1699,
  "longitude": 24.9384,
  "address": "66ebceb6648c738ce46894ce"
}

### Delete location
DELETE {{host}}{{apiversion}}/locations/66ebcc73dc764104700dced7