@host = http://localhost:3003

### Create a new location
POST {{host}}/api/locations
Content-Type: application/json

{
  "latitude": 60.1699,
  "longitude": 24.9384,
  "address": {
    "country": "Finland",
    "city": "Helsinki",
    "district": "Kallio",
    "post_code": "00530"
  }
}

### Get All locations
GET {{host}}/api/locations

### Get location by ID
GET {{host}}/api/locations/66e746c8ef8f1c8ffcc722ed

### Update location
PUT {{host}}/api/locations/66e3452b9d4ec19563785288
Content-Type: application/json

{
  "latitude": 60.1699,
  "longitude": 24.9384,
  "address": {
    "country": "Finland",
    "city": "Vaasa",
    "district": "Leipatehdas",
    "post_code": "65100"
  }
}

### Delete location
DELETE {{host}}/api/locations/66e93c898ef08c78a744a331