@host = http://localhost:3003
@apiversion = /api/v1

### Create a new location
POST {{host}}{{apiversion}}/locations
Content-Type: application/json

{
  "latitude": 60.1699,
  "longitude": 24.9384,
  "address": {
    "country": "Finland",
    "city": "Helsinki",
    "district": "Kallio",
    "post_code": "00530"
  }
}

### Get All locations
GET {{host}}{{apiversion}}/locations

### Get location by ID
GET {{host}}{{apiversion}}/locations/66eae5264238b0599ec7e4a0

### Update location
PUT {{host}}{{apiversion}}/locations/66eae5264238b0599ec7e4a0
Content-Type: application/json

{
  "latitude": 60.1699,
  "longitude": 24.9384,
  "address": {
    "country": "Finland",
    "city": "Vaasa",
    "district": "Leipatehdas",
    "post_code": "65100"
  }
}

### Delete location
DELETE {{host}}{{apiversion}}/locations/66eaf196e731e0ad487d5269