@host = http://localhost:3003
@apiversion = /api/v1
@userId = 66e4736af452f73c4fdb0196

### Create a new user
POST {{host}}{{apiversion}}/users 
Content-Type: application/json

{
  "name": "Bob Anderson",
  "email": "bob.anderson@example.com",
  "password": "Password123!",
  "role": "user"
}

### Update user password by ID
PUT {{host}}{{apiversion}}/users/{{userId}}/update-password
Content-Type: application/json

{
    "currentPassword": "Password123!",
    "newPassword": "Password1234!"
}

### Get all users (with pagination)
GET {{host}}{{apiversion}}/users?page=1&limit=10

### Get a user by ID
GET {{host}}{{apiversion}}/users/{{userId}}

### Update a user by ID
PUT {{host}}{{apiversion}}/users/{{userId}}
Content-Type: application/json

{
  "name": "Michael Smith Updated",
  "email": "michael.smith@example.com"
}

### Delete a user by ID
DELETE {{host}}{{apiversion}}/users/{{userId}}