@host = http://localhost:3003
@userId = 66e46898ac0bace7afcc0dd3

### Create a new user
POST {{host}}/api/users 
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john@example.com",
  "password": "Password123",
  "role": "user"
}

### Get all users (with pagination)
GET {{host}}/api/users?page=1&limit=10

### Get a user by ID
GET {{host}}/api/users/{{userId}}

### Update a user by ID
PUT {{host}}/api/users/{{userId}}
Content-Type: application/json

{
  "name": "John Updated",
  "email": "johnupdated@example.com"
}

### Delete a user by ID
DELETE {{host}}/api/users/{{userId}}